routes/web.php
    Route::get('fetch-attendance-details/{Emp_Code}/{month}', [App\Http\Controllers\Admin\Attendance\EmployeeAbsent::class, 'fetchAttendanceDetails'])
        ->name('fetch-attendance-details');

    Route::get('leave/delete', [App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class, 'removePendingLeave'])->name('remove-pending-leave');
    Route::post('leave/delete', [App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class, 'storeRemovePendingLeave'])->name('store-remove-pending-leave');

    Route::post('add-leave/list', [App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class, 'list'])->name('add-leave.list');
    Route::resource('add-leave', App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class);
    Route::get('fetch-employee-details-leave/{Emp_Code}/{month}', [App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details-leave');

    Route::get('leave/approve/static', [App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class, 'leaveApproveStatic'])->name('leave-approve-static');
    Route::post('leave/approve/static', [App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class, 'storeLeaveApproveStatic'])->name('store-leave-approve-static');

    Route::resource('leave-approval', App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class);
    Route::get('approve-leave/{id}', [App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class, 'ApproveLeave'])
        ->name('approve-leave');

    Route::post('add-attendance-excel/add-absent/store', [App\Http\Controllers\Admin\Attendance\AttendanceExcelController::class, 'storeImportAbsent'])->name('add-attendance-excel.absent');
    Route::get('add-attendance-excel/leave/delete', [App\Http\Controllers\Admin\Attendance\AttendanceExcelController::class, 'deleteAllImportAbsent'])->name('add-attendance-excel.absent.delete');
    Route::post('add-attendance-excel/leave/delete', [App\Http\Controllers\Admin\Attendance\AttendanceExcelController::class, 'postDeleteAllImportAbsent'])->name('add-attendance-excel.absent.post-delete');
    Route::resource('add-attendance-excel', App\Http\Controllers\Admin\Attendance\AttendanceExcelController::class);


    // Route::get('reject-leave/{id}', [App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class, 'RejectLeave'])
    // ->name('reject-leave');
    // End Attendance Management

    // Freeze Attendance
    Route::resource('freeze-attendance', App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class);
    Route::get('employee-monthly-salary/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'showEmployeeSalary'])->name('employee-monthly-salary.showEmployeeSalary');
    Route::get('unfreeze-employee', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'unfreezeEmployee'])->name('unfreeze-employee');
    Route::get('freeze-employee', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'freezeEmployee'])->name('freeze-employee');

    Route::get('fetch-date-range/{month}', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'fetchDateRange'])
        ->name('fetch-date-range');
    // Freeze Attendance End

    // Supplimentary Bill Leave
    Route::get('supplimentary-leave-bill/fetch/details', [App\Http\Controllers\Admin\Employee\SupplimentaryLeaveController::class, 'fetchDetails'])->name('supplimentary-leave-bill.fetch-details');

    Route::get('supplimentary-leave-bill/fetch/update-details', [App\Http\Controllers\Admin\Employee\SupplimentaryLeaveController::class, 'fetchUpdateDetails'])->name('supplimentary-leave-bill.fetch-update-details');

    Route::post('supplimentary-leave-bill/generate/store', [App\Http\Controllers\Admin\Employee\SupplimentaryLeaveController::class, 'storeGenerate'])->name('supplimentary-leave-bill.store-generate');
    Route::resource('supplimentary-leave-bill', App\Http\Controllers\Admin\Employee\SupplimentaryLeaveController::class);
    // End of Supplimentary Bill Leave

    // Calculated regeneration Suplimentry leave bill
    Route::resource('supplimentary-calculate', App\Http\Controllers\Admin\Employee\SupplimentaryLeaveCalculateController::class);
    // End of Calculated regeneration Suplimentry leave bill

    // Supplimentary Bill
    Route::post('select-supplimentary-bill-no-of-days', [App\Http\Controllers\Admin\Employee\SupplimentaryController::class, 'fetchSupplimentaryBillNoofDays'])->name('select-supplimentary-bill-no-of-days');
    Route::resource('supplimentary-bill', App\Http\Controllers\Admin\Employee\SupplimentaryController::class);
    Route::get('fetch-employee-details-supplimentary/{ward}', [App\Http\Controllers\Admin\Employee\SupplimentaryController::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details-supplimentary');
    Route::resource('suspend-supplimentary-bill', App\Http\Controllers\Admin\Employee\SuspendSupplimentaryController::class);

    Route::get('supplementary-leave-count', [App\Http\Controllers\Admin\Employee\SupplimentaryLeaveCountReportController::class,'index'])->name('view-supp-leave-count');
    Route::post('supplementary-leave-count-list', [App\Http\Controllers\Admin\Employee\SupplimentaryLeaveCountReportController::class,'list'])->name('supp-leave-count.list');

    // Reports Start
    Route::get('salary-slips/view-salary/group/{lang?}', [App\Http\Controllers\Admin\Report\SalarySlipController::class, 'viewSalaryInGroup'])->name('view-ward-salary-slips');

    Route::resource('salary-slips', App\Http\Controllers\Admin\Report\SalarySlipController::class);
    Route::get('salary-slips-marathi/{Emp_Code}', [App\Http\Controllers\Admin\Report\SalarySlipController::class, 'salarySlipMarathi'])
        ->name('salary-slips-marathi');


    Route::get('bank-statement/pdf', [App\Http\Controllers\Admin\Report\BankStatementController::class, 'bankStatementPdf'])->name('reports.bank-statement-pdf');
    Route::get('bank-statement/excel', [App\Http\Controllers\Admin\Report\BankStatementController::class, 'bankStatementExcel'])->name('reports.bank-statement-excel');
    Route::resource('bank-statement', App\Http\Controllers\Admin\Report\BankStatementController::class);
    Route::resource('pay-sheet', App\Http\Controllers\Admin\Report\PaySheetController::class);
    Route::get('pay-sheet-pdf', [App\Http\Controllers\Admin\Report\PaySheetController::class, 'showPaySheetPDF'])->name('pay-sheet-pdf');

    Route::resource('yearly-pay-sheet', App\Http\Controllers\Admin\Report\YearlyPaySheetController::class);
    Route::get('yearly-pay-sheet-pdf/{emp_id?}/{finyear?}', [App\Http\Controllers\Admin\Report\YearlyPaySheetController::class, 'showPaySheetPDF'])->name('yearly-pay-sheet-pdf');
    // Route::get('yearly-pay-sheet-marathi-pdf/{emp_id?}/{finyear?}', [App\Http\Controllers\Admin\Report\YearlyPaySheetController::class, 'showPaySheetMarathiPDF'])->name('yearly-pay-sheet-marathi-pdf');
    Route::get('yearly-pay-sheet-marathi-pdf/{emp_id?}/{finyear?}', [App\Http\Controllers\Admin\Report\YearlyPaySheetController::class, 'generateYearlyPaysheetPdf'])->name('yearly-pay-sheet-marathi-pdf');


    Route::resource('bank-deduction-employee-report', App\Http\Controllers\Admin\Report\BankDeductionEmployeeController::class);
    Route::resource('bank-deduction-report', App\Http\Controllers\Admin\Report\BankDeductionController::class);
    Route::resource('summary-department-report', App\Http\Controllers\Admin\Report\GrandSummaryDepartmentController::class);
    Route::get('grand-summary-department-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryDepartmentController::class, 'showGrandSummaryDepartmentPDF'])->name('grand-summary-department-pdf');
    Route::resource('summary-ward-report', App\Http\Controllers\Admin\Report\GrandSummaryWardController::class);
    Route::get('grand-summary-ward-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryWardController::class, 'showGrandSummaryWardPDF'])->name('grand-summary-ward-pdf');
    Route::resource('summary-report', App\Http\Controllers\Admin\Report\GrandSummaryController::class);
    Route::get('grand-summary-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryController::class, 'showGrandSummaryPDF'])->name('grand-summary-pdf');
    Route::resource('pay-sheet-excel', App\Http\Controllers\Admin\Report\PaySheetExcelController::class);

    Route::resource('allowance-report', App\Http\Controllers\Admin\Report\AllowanceReportController::class);
    Route::get('deduction-report/pdf/{lang}', [App\Http\Controllers\Admin\Report\DeductionReportController::class, 'deductionReportPdf'])->name('deduction-report.pdf');
    Route::resource('deduction-report', App\Http\Controllers\Admin\Report\DeductionReportController::class);

    Route::resource('retirement-report', App\Http\Controllers\Admin\Report\RetirementController::class);
    // Reports End


    // Pension Start
    Route::resource('pension-item-master', App\Http\Controllers\Admin\Pension\PensionItemMasterController::class);
    Route::resource('manage-pensioner-payroll', App\Http\Controllers\Admin\Pension\ManagePensionerPayrollControler::class);

    Route::resource('pension', App\Http\Controllers\Admin\Pension\PensionController::class);

    Route::post('pension-new/datatable/list', [App\Http\Controllers\Admin\Pension\PensionNewController::class, 'list'])->name('pension-new.list');
    Route::resource('pension-new', App\Http\Controllers\Admin\Pension\PensionNewController::class);
    Route::resource('freeze-pension', App\Http\Controllers\Admin\Pension\FreezePensionController::class);
    Route::resource('freeze-pension-new', App\Http\Controllers\Admin\Pension\FreezePensionNewController::class);

resources/views/admin/supplimentary/add-regular-supplimentary-bill.blade.php
<x-admin.layout>
    <x-slot name="title">Generate Supplimentary Bill</x-slot>
    <x-slot name="heading">Generate Supplimentary Bill</x-slot>

    <!-- Add Form -->
    <div class="row" id="addContainer">
        <div class="col-sm-12">
            <form class="theme-form" name="addForm" id="addForm" enctype="multipart/form-data">
                @csrf
            <div class="card">
                <header class="card-header">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title">Supplimentary Bill</h4>
                        <button type="submit" class="btn btn-primary" id="addSubmit" disabled>Save</button>
                    </div>
                </header>

                <div class="card-body">
                    <div class="mb-3 row">

                        <div class="col-md-4">
                            <label class="col-form-label" for="bill_no">Bill No<span class="text-danger">*</span></label>
                            <input class="form-control" id="bill_no" name="bill_no" type="text" value="{{ $billNo }}" required readonly>
                            <span class="text-danger invalid bill_no_err"></span>
                        </div>
                        
                        <div class="col-md-4">
                            <label class="col-form-label" for="bill_description">Bill Description<span class="text-danger">*</span></label>
                            <input class="form-control" id="bill_description" name="bill_description" type="text" placeholder="Enter Bill Description" required>
                            <span class="text-danger invalid bill_description_err"></span>
                        </div>

                        <div class="col-md-4">
                            <label class="col-form-label" for="cheque_date">Select Cheque Date<span class="text-danger">*</span></label>
                            <input class="form-control datepicker" id="cheque_date" name="cheque_date" type="text" placeholder="Enter Employee Id" required readonly>
                            <span class="text-danger invalid cheque_date_err"></span>
                        </div>

                        <div class="col-md-4">
                            <label class="col-form-label" for="ward_id">Select Group<span class="text-danger">*</span></label>
                            <select name="ward_id" class="form-select" id="selectWardId" required>
                                <option value="">--Select--</option>
                                @foreach($wards as $ward)
                                <option value="{{ $ward->id }}">{{ $ward->name }}</option>
                                @endforeach
                            </select>
                            <span class="text-danger invalid ward_id_err"></span>
                        </div>
                        

                        <div class="col-md-4">
                            <label class="col-form-label" for="ward_id">Select Payment Status<span class="text-danger">*</span></label>
                            <select name="payment_status" class="form-select" required>
                                <option value="">--Select--</option>
                                <option value="1">Not Processed</option>
                                <option value="2">Processed & Not Paid</option>
                                <option value="3">Processed & Paid</option>
                            </select>
                            <span class="text-danger invalid ward_id_err"></span>
                        </div>                      
                    </div>

                </div>
                <div class="card-footer d-none">
                    <div class="table-responsive">
                        <table id="dataTable" class="table table-bordered nowrap align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" id="selectAll" class="form-check-input">
                                    </th>
                                    <th>Employee Code</th>
                                    <th>Employee Name</th>
                                    <th>Department</th>
                                    <th>Group Name</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>


</x-admin.layout>


{{-- Add --}}
<script>
    // $('#dataTable').DataTable();

    $("#addForm").submit(function(e) {
        e.preventDefault();
        if ($('input[name="emp_code[]"]:checked').length === 0) {
            alert('Please select at least one employee.');
            return false;
        }
        $("#addSubmit").prop('disabled', true);

        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('supplimentary-bill.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function(data) {
                $("#addSubmit").prop('disabled', false);
                if (!data.error2)
                    swal("Successful!", data.success, "success")
                    .then((action) => {
                        window.location.href = '{{ route('supplimentary-bill.index') }}';
                    });
                else
                    swal("Error!", data.error2, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            }
        });

    });


    $(document).ready(function() {
        $("#selectWardId").change(function() {
            var group = $(this).val();
            
            if (group != '') {
                var url = "{{ route('fetch-employee-details-supplimentary', ':group') }}";

                $.ajax({
                    url: url.replace(':group', group),
                    type: 'GET',
                    data: {
                        '_method': "GET",
                        '_token': "{{ csrf_token() }}"
                    },
                    success: function(data) {
                        if (!data.error) {
                            $('#dataTable tbody').empty();
                            var html = "";
                            $.each(data.employee_details, function(key, value){
                                html += `
                                    <tr>
                                        <td>
                                            <input type="checkbox" class="d-none departmentId" name="department_id[]" value="${value.department_id}" />
                                            <input type="checkbox" class="d-none employeeId" name="employee_id[]" value="${value.id}" />
                                            <input type="checkbox" name="emp_code[]" value="${value.employee_id}" class="form-check-input emp_code_input">
                                        </td>
                                        <td>${value.employee_id}</td>
                                        <td>${value.fname} ${value.mname} ${value.lname}</td>
                                        <td>${value?.department?.name}</td>
                                        <td>${value?.ward?.name}</td>
                                </tr>`;
                            });

                            if ($.fn.DataTable.isDataTable('#dataTable')) {
                                $('#dataTable').DataTable().destroy();
                            }
                         
                            $('#dataTable tbody').html(html);
                            // Check if DataTable already exists and destroy it
                            

                            // Reinitialize DataTable
                            $('#dataTable').DataTable({
                                'paging' : false,
                                'columnDefs': [
                                    { 
                                        'orderable': false, 
                                        'targets': 0 
                                    }
                                ]
                            });
                            $('.card-footer').removeClass('d-none');
                            $('#addSubmit').prop('disabled', false);
                        }else{
                            alert('Employee not found')
                            $('.card-footer').addClass('d-none');
                            $('#addSubmit').prop('disabled', true);
                        }
                    },
                    error: function(error, jqXHR, textStatus, errorThrown) {
                        swal("Error!", "Something went wrong", "error");
                    },
                });
            } else {
                $('#dataTable tbody').empty();
                $('.card-footer').addClass('d-none');
                $('#addSubmit').prop('disabled', true);
            }

        });
    });

    $(document).ready(function(){
        $('#selectAll').change(function(){
            
            if(this.checked){
                $('body').find('.emp_code_input').prop('checked', true);
            }else{
                $('body').find('.emp_code_input').prop('checked', false);
            }
        });

        $('body').on('change', '.emp_code_input', function(){
            if(this.checked){
                $(this).closest("td").find('.departmentId').prop('checked', true);
                $(this).closest("td").find('.employeeId').prop('checked', true);
            }else{
                $(this).closest("td").find('.departmentId').prop('checked', false);
                $(this).closest("td").find('.employeeId').prop('checked', false);
            }
        });
    });
</script>

resources/views/admin/supplimentary/regular-supplimentary-bill.blade.php
<x-admin.layout>
    <x-slot name="title">Supplimentary Bill</x-slot>
    <x-slot name="heading">Supplimentary Bill</x-slot>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                @can('supplimentary-bill.create')
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="">
                                    @if($type == 1)
                                        <a href="{{ route('supplimentary-bill.create') }}" id="addToTable1" class="btn btn-primary">Add <i class="fa fa-plus"></i></a>
                                    @else
                                        <a href="{{ route('suspend-supplimentary-bill.create') }}" id="addToTable1" class="btn btn-primary">Add <i class="fa fa-plus"></i></a>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                @endcan
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="dataTable" class="table table-bordered nowrap align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                    <th>Bill No</th>
                                    <th>Bill Description</th>
                                    <th>Group</th>
                                    <th>Cheque Date</th>
                                    <th>Payment Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    @push('scripts')
        <script>
            $(document).ready(function(){
                $('#dataTable').DataTable({
                    pageLength: 10,
                    info: false,
                    legth: false,
                    "autoWidth": false,
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: "{{ route('supplimentary-bill.index') }}",
                    },
                    columns: [
                        {
                            data: 'DT_RowIndex',
                            name: 'DT_RowIndex',
                            class: 'xs-hidden',
                            orderable: false,
                            searchable: false,
                            render: function(data, type, row){
                                return data;
                            },
                        },
                        {
                            data: 'bill_no',
                            name: 'supplimentary_bills.bill_no',
                            orderable: false,
                            render: function(data, type, row){
                                return data;
                            },
                        },
                        {
                            data: 'bill_description',
                            name: 'bill_description',
                            orderable: true,
                            render: function(data, type, row){
                                return data;
                            },
                        },
                        {
                            data: 'ward',
                            name: 'ward.name',
                            orderable: true,
                            render: function(data, type, row){
                                return data;
                            },
                        },
                        {
                            data: 'cheque_date',
                            name: 'cheque_date',
                            orderable: true,
                            render: function(data, type, row){
                                return data;
                            },
                        },
                        {
                            data: 'payment_status',
                            name: 'payment_status',
                            orderable: true,
                            render: function(data, type, row){
                                if(data == "1"){
                                    return "Not Processed";
                                }else if(data == "2"){
                                    return "Processed & Not Paid";
                                }else if(data == "3"){
                                    return "Processed & Paid";
                                }else{
                                    return "-";
                                }
                            },
                        },
                        {
                            data: 'id',
                            name: 'id',
                            orderable: false,
                            render: function(data, type, row){
                                let html = `
                                    <button class="edit-element btn btn-primary px-2 py-1" title="Edit category" data-id="${data}">
                                        Edit
                                    </button>
                                    
                                    <button class="btn btn-danger rem-element px-2 py-1" title="Delete category" data-id="${data}">
                                        Delete
                                    </button>`;
                                return html;
                            },
                        },
                    ]
                });
            })
        </script>
        @endpush


</x-admin.layout>

<!-- Delete -->
<script>
    $("#buttons-datatables").on("click", ".rem-element", function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure to delete this Supplimentary Bill?",
                // text: "Make sure if you have filled Vendor details before proceeding further",
                icon: "info",
                buttons: ["Cancel", "Confirm"]
            })
            .then((justTransfer) => {
                if (justTransfer) {
                    var model_id = $(this).attr("data-id");
                    var url = "{{ route('supplimentary-bill.destroy', ':model_id') }}";

                    $.ajax({
                        url: url.replace(':model_id', model_id),
                        type: 'POST',
                        data: {
                            '_method': "DELETE",
                            '_token': "{{ csrf_token() }}"
                        },
                        success: function(data, textStatus, jqXHR) {
                            if (!data.error && !data.error2) {
                                swal("Success!", data.success, "success")
                                    .then((action) => {
                                        window.location.reload();
                                    });
                            } else {
                                if (data.error) {
                                    swal("Error!", data.error, "error");
                                } else {
                                    swal("Error!", data.error2, "error");
                                }
                            }
                        },
                        error: function(error, jqXHR, textStatus, errorThrown) {
                            swal("Error!", "Something went wrong", "error");
                        },
                    });
                }
            });
    });
</script>